# Generated by Django 3.2.5 on 2021-07-15 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_friend'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('user', 'friend')},
        ),
    ]
